# Monitor Configuration
monitor.host=jcswebt11.ftn.fedex.com,jcswebt111.ftn.fedex.com,jcswebt112.ftn.fedex.com
monitor.port=443
monitor.timeout-millis=3000
monitor.interval-seconds=30
monitor.failures-before-alert=3
monitor.alert-cooldown-minutes=1

# SMTP Configuration
spring.mail.host=mapper.gslb.fedex.com
monitor.smtp.port=587
monitor.smtp.start-tls=true
monitor.smtp.from=jupiter_webServer_alert@fedex.com
monitor.smtp.to=pradeep.ramaiah.osv@fedex.com, pradeep.a.ramaiah@accenture.com

